name: Reusable workflow example

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      repo:
        required: true
        type: string
    secrets:
      token:
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: "jonathanCS-org/called-repo"
        token: ${{secrets.token}}
        ref: main
    - name: Find and replace repo version
      run: |
        # Variables
        REPO="${{ inputs.repo }}"
        VERSION="${{ inputs.version }}"

        # Find and replace any occurrences of <repo>/module?ref=<old-version> with <repo>/module?ref=<new-version>
        find . -type f -name "*.txt" -exec sed -i "s|${REPO}/module?ref=[^&]*|${REPO}/module?ref=${VERSION}|g" {} +
    - name: Output updated file
      run: |
       cat version.txt
    - name: Create branch and check it out
      run: |
       git config --global user.name 'GitHub Actions'
       git config --global user.email 'githubaction@github.com'
       git checkout -b chore/update-version 
       git add .
       git commit -m "version update"
       git push --set-upstream origin chore/update-version
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
    - name: Create pull request
      run: gh pr create -B main -H chore/update-version --title 'Merge chore/update-version into main' --body 'Created by Github action'
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3.10.0
    #   with:
    #     token: ${{ secrets.token }}
    #     commit-message: Update version
    #     title: '[Example] Update version'
    #     body: >
    #       This PR is auto-generated by 
    #       [create-pull-request](https://github.com/peter-evans/create-pull-request).
    #     labels: feature, automated pr
    #     branch: feature/workflow-demo